version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    # environment:
    #   - SEGMENT_WRITE_KEY=${SEGMENT_WRITE_KEY}
    volumes:
      - .:/usr/src/app
